### ISSUE TITLE
Pass 'R CMD CHECK'

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/crunchtabs#1]
See https://travis-ci.org/Crunch-io/crunchtabs/jobs/209846431 for a recent build on Travis. Lots of man/namespace issues. Among the ones I see are:

* Missing imports from base packages
* Other functions/objects referenced that don't exist (fixed a bunch by deleting unused functions in https://github.com/Crunch-io/crunchtabs/commit/bf4d3497ec502ea43fc108ea3ce25cd6b07c6fce)
* Bad S3 documentation; mismatched signatures for the different methods
* Invalid DESCRIPTION file

The method documentation can be a little tricky. What I've done for S4 is to define documentation separate from the methods and give it a `@name`, like https://github.com/Crunch-io/rcrunch/blob/master/R/dataset-catalog.R#L75. Then you link all methods you want to go with it to it like this: https://github.com/Crunch-io/rcrunch/blob/master/R/dataset-catalog.R#L78-L79.

**Comment by ksedr** [comment]
The current version of the package passes 'R CMD CHECK'.
