### ISSUE TITLE
more tests!

### ISSUE THREAD

**Issue by npelikan** [Crunch-io/crunchtabs#11]
add more tests, especially around MRs

**Comment by 1beb** [comment]
Can be marked as complete when each file is at least 85% covered. 

- [ ] Target 85% Overall (crunchtabs Coverage: 67.78%)
- [ ] R/crunchtabs.R: 0.00%
- [ ] R/banner.R: 1.49%
- [ ] R/crosstabs.R: 2.17%
- [ ] R/utils.R: 14.29%
- [ ] R/getters.R: 15.00%
- [ ] R/tabBooks.R: 21.16%
- [ ] R/forNowTransforms.R: 37.78%
- [ ] R/writeExcel.R: 78.09%
- [ ] R/theme.R: 80.10%
- [ ] R/tex.R: 83.64%
- [ ] R/tex-table.R: 84.45%
- [x] R/reformatResults.R: 90.95%
- [x] R/writeLatex.R: 95.57%
