### ISSUE TITLE
Presentation of multiple response in toplines

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/crunchtabs#13]
Joe Williams reports in an email to support@crunch.io (emphasis added):

> Data export from Gryphon to Crunch with dyngrid-check / grid-check problems is problematic.  Variables are not bound together as would be expected for a grid type question.  Instead, the grid-check subvariables are treated as stand alone variables in a separate folder with the label of the grid.  The new stand alone variables take the description of the grid-check variable.  The label for the new stand alone variables are the subvariable labels from the original grid-check question.  Unexpected treatment, but not catastrophic. **However, when creating a pdf using Crunch tabs, the toplines do not identify the subvariable being asked about.  Also, the crosstabs, for some reason count the "No" response as part of the unweighted N.  Rather than presenting an N, the crosstabs give percentages.**

Sounds like an issue/request with this package, so I'm redirecting here. If you find that there's something for us to look into in `crunch` with multiple response handling, please let us know.

**Comment by npelikan** [comment]
@nealrichardson to me it sounds a bit upstream from us. To us, the variables look no different than your run-of-the-mill MRs in a folder. I know (based on an irl convo with Joe) that the **eventual** plan is to bind grid-checks into MR arrays on export. For now, I think the best solution lies with Fernando's team, in that G4 export of grid-checks could append the subvariable name to the question wording for each of these created variables.

**Comment by nealrichardson** [comment]
Fine with me to close; I just wanted to pass along the concern. If you've spoken to Joe and he doesn't think there's anything else to do (I asked for clarification and didn't get any), then great.

**Comment by npelikan** [comment]
Thanks for letting us know!
