### ISSUE TITLE
Error from writeExcel() in package crunchtabs

### ISSUE THREAD

**Issue by xinling-zhang** [Crunch-io/crunchtabs#16]
I was trying to export reports from crunch using package **crunchtabs**. I could export pdf report correctly. But I got an error when I exported excel report.

Without option **proportions = TRUE** in function **writeExcel()**,  there is no error. But I want to see proportions rather than count in the excel report. 

With option **proportions = TRUE** in function **writeExcel()**,  there is an error as below: 

Error in names(object) <- nm : 
  'names' attribute [4] must be the same length as the vector [1]

**Comment by persephonet** [comment]
Hi Xinling! Thanks so much for submitting your issue. 
Could you please create a minimum reproducible example? Please use a commonly available crunch dataset, like  https://app.crunch.io/dataset/c520d0944d3a41c285da408e76f0ebb4/ .

If you find that the error only occurs on this specific dataset, would you please share the dataset and dataset id with myself, nick.pelikan, and stewart.wright? 

Finally, can you please let me know exactly what code you were running when you got this error (i.e the loadDataset, banner, crosstabs, and writeExcel functions)? Please be sure to strip out any yougov- or client- specific code from your post, as these issues are visible to the world. Thanks so much, and apologies for the back and forth, we're currently working up some submission guidelines to make the bug reporting process as seamless as possible :)

**Comment by xinling-zhang** [comment]
Hi Persephonet, I got a similar error when I ran function **writeExcel** on the dataset as below:

**Error in setNames(as.data.frame(if (proportions) x$totals_proportions else x$totals_counts),  : 
  'names' attribute [2] must be the same length as the vector [1]**

```
##############
devtools::install_github("Crunch-io/crunchtabs")
library(crunch)
library(crunchtabs)
login()

ds <- loadDataset("Example Dataset")

banner1 <- banner(ds, vars = list(
  Demographics = c("age2", "age3"),
  Other = c("allpets", "favpet"))
)

tabout <- crosstabs(ds, weight = 'weight', banner = banner1)
writeExcel(tabout, 
           filename = "Tabs", 
           proportions=TRUE,
           table_of_contents = TRUE,
           show_grid_lines = TRUE,
           digits = 0,
           subtitle = paste("Pets"))

logout()
```

**Comment by persephonet** [comment]
Hi qj007 thank you! Please try installing the names-error branch and let me know if that works for you. We'll get it merged into the master as soon as we can!

Thanks,
Persephonet
