### ISSUE TITLE
Rounding totals in PDF reports

### ISSUE THREAD

**Issue by jamesmartherus** [Crunch-io/crunchtabs#189]
Currently, when generating PDF reports, totals are sometimes just above or just below 100%. Currently, the argument ``latex_round_percentages = TRUE``

rounds down but not up. For example, 101% rounds down to 100%, but 99% remains unchanged in the report. It would be great if this argument rounded percentages both down and up to 100%.

**Comment by 1beb** [comment]
Hi James! Thank you for your report. I've added an option to issue_185 branch that allows you to enforce the presentation of 100% in the totals row. 

```
myTheme <- themeNew(..., enforce_onehundred = TRUE)
```

We'll include this in the next release. For the time being you can install this using: 

```
devtools::install_github("crunch-io/crunchtabs", ref = "issue_185")
```
