### ISSUE TITLE
Feature request: hypothesis testing

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/crunchtabs#20]
Testing each category against the other categories for that variable. This is what clients have gotten traditionally and is what they expect.

**Comment by GitBrianLaw** [comment]
Just want to add this: sigh

**Comment by malecki** [comment]
Depends on implementation of https://github.com/Crunch-io/rcrunch/issues/203

**Comment by 1beb** [comment]
Old issue, closing.
