### ISSUE TITLE
Logo/branding should be parametrized

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/crunchtabs#3]
Find everywhere you have "YouGov" in the code and consider how that can be made an option. Perhaps function parameters, probably with a default that is `getOption("something")` so that you can set those values/paths in your .Rprofile and not have to pass them in every time.

**Comment by persephonet** [comment]
I looked through every file in the R folder and didn't see anything that said "YouGov" so I'm guessing Kamil did this and didn't close the issue. If I missed something, let me know and I'll reopen the issue.
