### ISSUE TITLE
Feature request: tabs export in MS Word

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/crunchtabs#30]
Client at Harvard "tabs export in Word would be _huge_". 

Brainstorming, is it possible to take the pdf then force that to "open" in Word (as an image?) ? If not that, then I'm dubious about Word's built in "tables". Another alternative would be export to google docs which might be easier to work with and then they can export to Word from there if they really really need to. 

Thank you.

**Comment by 1beb** [comment]
This is possible. Extracting the tabs as images and placing them in word or powerpoint. Unclear if this is desired. crunch.io functionality for creating "slides" may be more user friendly.
