### ISSUE TITLE
Use of double quotation marks in G4 questionnaire leads to errors in latex/pdf creation

### ISSUE THREAD

**Issue by joewilliams-yg** [Crunch-io/crunchtabs#34]
Clients ask questions that involve quotes and use double quotation marks in the wording.  However, crunchtabs will throw an error if it encounters double quotation marks.  Current work around is to replace double quotation marks with single quotation marks, but that seems less than ideal.  Is there a way for crunchtabs to identify double quotation marks and handle without error?

**Comment by nealrichardson** [comment]
Hi Joe, I'm in here looking at a few other issues now and saw this one. Do you have an example of something that fails and what the error looks like?

**Comment by 1beb** [comment]
Closing. Solved by previous version as per @joewilliams-yg
