### ISSUE TITLE
Newline characters in variable name and description cause latex compiler to crash

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/crunchtabs#36]
Hello, 

TargetSmart is testing this and found that if there is a newline character inside a variable name or description then the latex compiler crashes. I have not had a chance to build a minimum reproducible example yet (and will try to today) but wanted to file this now in case you can see the issue right away. 

Here is an example from the .tex file, sorry I don't have their dataset yet.

\begin{center}
\begin{longtable}{p{0.3in}p{5.5in}}
\addcontentsline{lot}{table}{ 8. Q. 9 Now, I'd like to rate your feelings toward some people, with one hundred meaning a VERY WARM, FAVORABLE feeling; zero meaning a VERY COLD, UNFAVORABLE feeling; 

and fifty meaning not particularly warm or cold. You can use any number from zero to one hundred, the higher the number the more favorable your feelings are toward that person. If you have no opinion or have never heard of that person, please say so.  (IF DON'T KNOW) Would you say you are unable to give an opinion of (READ BELOW), or have you never heard of (READ BELOW)? 

(NO OPINION/DK = 101) (NEVER HEARD = 102)

(RANDOMIZE)}
\hangindent=0em \parbox{6.5in}{
\formatvardescription{8. Q. 9 Now, I'd like to rate your feelings toward some people, with one hundred meaning a VERY WARM, FAVORABLE feeling; zero meaning a VERY COLD, UNFAVORABLE feeling; and fifty meaning not particularly warm or cold. You can use any number from zero to one hundred, the higher the number the more favorable your feelings are toward that person. If you have no opinion or have never heard of that person, please say so. 

(IF DON'T KNOW) Would you say you are unable to give an opinion of (READ BELOW), or have you never heard of (READ BELOW)? 

(NO OPINION/DK = 101) (NEVER HEARD = 102) 

(RANDOMIZE)}} \\\longtablesep

 & 0-10 \hspace*{0.15em} \dotfill 8\%\\
 & 10-20 \hspace*{0.15em} \dotfill 1\%\\
 & 20-30 \hspace*{0.15em} \dotfill 1\%\\
 & 30-40 \hspace*{0.15em} \dotfill 2\%\\
 & 40-50 \hspace*{0.15em} \dotfill 2\%\\
 & 50-60 \hspace*{0.15em} \dotfill 12\%\\
 & 60-70 \hspace*{0.15em} \dotfill 3\%\\
 & 70-80 \hspace*{0.15em} \dotfill 6\%\\
 & 80-90 \hspace*{0.15em} \dotfill 3\%\\
 & 90-100 \hspace*{0.15em} \dotfill 2\%\\
 & 100-110 \hspace*{0.15em} \dotfill 60\% \\
   & Totals \hspace*{0.15em} \dotfill 100\% \\
 & Unweighted N \hspace*{0.15em} \dotfill 350 \\

\end{longtable}
\end{center}

I googled around and found this [page](https://tex.stackexchange.com/questions/458442/why-does-latex-throw-an-error-when-there-is-empty-lines-inside-the-caption-envir/458443) which seems to have the answer, that is to manually remove the newlines from the .tex file (I didn't follow the insert [zz] thing in this page, that didn't seem to do it). And so if you had some QC step that removes those newlines, then the .tex file that generates should be fine.

**Comment by nealrichardson** [comment]
Perhaps it would work to replace all `\n` with `\\` (the LaTeX newline)?

I see there already is a function used to escape text inputs going into the .tex, so maybe add to that? https://github.com/Crunch-io/crunchtabs/blob/master/R/writeLatex.R#L193

**Comment by GitBrianLaw** [comment]
Confirmed. It was a new line (\n) in the description that causes this problem. 

Regarding timing of a fix, they are evaluating us and next week will decide likely whether to proceed and so if they do go ahead, we would want to fix this as soon as possible after that.

**Comment by nealrichardson** [comment]
@GitBrianLaw I think https://github.com/Crunch-io/crunchtabs/commit/a1145270d0a9a6bb62de7dde973e2f72f7b13745 should fix the issue but I don't have a good failing test case to confirm; can you pull the latest and try before we declare victory?

**Comment by nealrichardson** [comment]
Ok I reproduced the issue, got a simple test, and fixed it.
