### ISSUE TITLE
Feature request from client

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/crunchtabs#37]
Focusing on writelatex for toplines here.

Currently, we use long table to extend a table that would run across the bottom of a page. A client would rather have it be so that long table did not intervene and if a new table would have to be spread across multiple pages, then instead it would skip to a new page and start from the top of that page. 

I asked them, what about a scenario where you have a table so long that even if it starts on a new page for itself it would run off? They said, then in those cases it's ok to do long table. So might be fairly complicated what they want. They also said that it "almost never" happens in their work where a table that was given a whole new page would run off, but that's specific to them.

**Comment by 1beb** [comment]
Tracking this in #56
