### ISSUE TITLE
Fix Travis CI environment

### ISSUE THREAD

**Issue by ksedr** [Crunch-io/crunchtabs#6]
R CMD check fails with an error on a Travis worker instance:
`Error: package 'testthat' was installed by an R version with different internals; it needs to be reinstalled for use with this R version`

**Comment by nealrichardson** [comment]
See https://github.com/travis-ci/travis-ci/issues/8409; due to a recent change in the R development version, you need to reset your Travis cache.

**Comment by ksedr** [comment]
Fixed. Thanks, Neal!
