### ISSUE TITLE
Error from function crosstabs()

### ISSUE THREAD

**Issue by xinling-zhang** [Crunch-io/crunchtabs#9]
I got an error as below when I ran toplines. After I excluded variables of type multiple-response, crosstabs() worked. FYI, the category names of those multiple-response variables are "selected" and "not selected". I also tried "Selected" and "not selected", but I got the same error.

[crunch] > toplines <- crosstabs(ds, weight = 'weight')
Error in ret$proportions[, "Selected"] : incorrect number of dimensions
In addition: Warning message:
In crosstabs(ds, weight = "weight") :
  Variables of types: text, datetime are not supported and have been skipped

[crunch] > self(ds)
[1] "https://app.crunch.io/api/datasets/76683330d4c24ee9b84a2b211b9f996b/"

**Comment by persephonet** [comment]
This should be fixed now. Please update and let me know if it works.

**Comment by xinling-zhang** [comment]
I still got the same error this morning when I included multiple response variables for toplines.

**Comment by xinling-zhang** [comment]
The error has been fixed. Thank you.
